### ISSUE TITLE
How to shrink the left margin using cayman theme

### ISSUE THREAD

**Issue by steveb-cirina** [yixuan/prettydoc#17]
Hi

I am using the "cayman" theme with the following YAML:

```
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
```

I find that the left margin (the white space before the content) is quite large, is there a way to shrink (resize) this ?

I have googled this but didn't find anything that helped.

Thanks!

**Comment by yixuan** [comment]
For the current unpublished version in the `master` branch, you can add a customized CSS with the following content:

```css
.main-content, .toc {
    max-width: 80rem;
}
```

You may adjust the value according to your own need. The default value in the theme is `64rem`.
