### ISSUE TITLE
prettydoc: about scrolling catalogue in html and head-hiding in markdown

### ISSUE THREAD

**Issue by huangwb8** [yixuan/prettydoc#37]
Hello, I found prettydoc a useful tool for beautiful html production.
Here's some usage problems I meet.

1. Could the head of the markdown hided automatically in the .md?
```
---
title: "XXX"
author: "XXX"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    math: katex
    keep_md: true
---
```

2. In the .html, could a scrolling catalogue possible?

Thank you very much!
